import { BitcoinEvent } from "./events";
import { Country, Currency } from "./global";
import { PaymentMethodCountry } from "./offer";

export type PaymentMethodField =
  | "accountNumber"
  | "bankAccountNumber"
  | "bankBranch"
  | "bankName"
  | "beneficiary"
  | "beneficiaryAddress"
  | "bic"
  | "bsbNumber"
  | "cedulaID"
  | "DNI"
  | "email"
  | "iban"
  | "lnurlAddress"
  | "name"
  | "nameTag"
  | "phone"
  | "pixAlias"
  | "postePayNumber"
  | "receiveAddress"
  | "reference"
  | "routingDetails"
  | "RUT"
  | "steamFriendCode"
  | "ukBankAccount"
  | "ukSortCode"
  | "userId"
  | "userName"
  | "wallet";

export type PaymentMethod =
  | "accrue"
  | "advcash"
  | "airtelMoney"
  | "alias"
  | "apaym"
  | "bancolombia"
  | "bankera"
  | "bizum"
  | "blik"
  | "cbu"
  | "chileBankDeposit"
  | "chippercash"
  | "cvu"
  | "daviPlata"
  | "djamo"
  | "eversend"
  | "fasterPayments"
  | "friends24"
  | "giftCard.amazon"
  | `giftCard.amazon.${PaymentMethodCountry}`
  | "giftCard.steam"
  | "guatemalaBankDeposit"
  | "instantSepa"
  | "iris"
  | "kcbBankKenya"
  | "keksPay"
  | "klasha"
  | "liquid"
  | "lnurl"
  | "lydia"
  | "m-pesa"
  | "mbWay"
  | "mercadoPago"
  | "mobilePay"
  | "moov"
  | "mtn"
  | "n26"
  | "nationalTransferBG"
  | "nationalTransferCH"
  | "nationalTransferCZ"
  | "nationalTransferDK"
  | "nationalTransferHU"
  | "nationalTransferIS"
  | "nationalTransferNG"
  | "nationalTransferNO"
  | "nationalTransferPL"
  | "nationalTransferRO"
  | "nationalTransferSE"
  | "nationalTransferSG"
  | "nationalTransferTR"
  | "nequi"
  | "neteller"
  | "orangeMoney"
  | "osko"
  | "papara"
  | "paraguayBankTransfer"
  | "payday"
  | "payeer"
  | "payID"
  | "payLah"
  | "paylib"
  | "paypal"
  | "paysera"
  | "paytm"
  | "perfectMoney"
  | "peruBankDeposit"
  | "pix"
  | "postePay"
  | "rebellion"
  | "revolut"
  | "satispay"
  | "sepa"
  | "sinpe"
  | "sinpeMovil"
  | "skrill"
  | "spei"
  | "stp"
  | "straksbetaling"
  | "strike"
  | "swish"
  | "tigoMoneyBolivia"
  | "tigoMoneyElSalvador"
  | "tigoMoneyGuatemala"
  | "tigoMoneyHonduras"
  | "tigoMoneyParaguay"
  | "tigoPesa"
  | "twint"
  | "UPI"
  | "vipps"
  | "wave"
  | "westernUnion"
  | "wirepay"
  | "wise"
  | `cash.${BitcoinEvent["id"]}`;

export type PaymentMethodInfo = {
  id: PaymentMethod;
  currencies: Currency[];
  fields: {
    mandatory: PaymentMethodField[][][];
    optional: PaymentMethodField[];
  };
  countries?: Country[];
  rounded?: boolean;
  anonymous: boolean;
};
export type PaymentData = {
  id: string;
  label: string;
  type: PaymentMethod;
  currencies: Currency[];
  country?: PaymentMethodCountry;
  hidden?: boolean;
  reference?: string;
};
export type MeansOfPayment = Partial<Record<Currency, PaymentMethod[]>>;
